[build]
  publish = "dist"
  command = "yarn run generate --no-lock && yarn run build:api"
  functions = "./functions"
[build.environment]
  NODE_VERSION = "9" 
  YARN_FLAGS = "--no-ignore-optional"
[template.environment]
  API_URL = "https://easeout.co"
  SENDGRID_API_KEY = "Your Sendgrid API Key (required for newsletter signup box)"
  SENDGRID_WELCOME_SENDER_EMAIL = "Sendgrid Welcome Sender Email"
  SENDGRID_WELCOME_SENDER_NAME = "Sendgrid Welcome Sender Name"
  SENDGRID_WELCOME_TEMPLATE_ID = "Sendgrid Welcome Email Template ID"
[[redirects]]
  from = "https://jolly-nightingale-875959.netlify.com"
  to = "https://easeout.co"
  status = 301
  force = true
[[redirects]]
  from = "/tags"
  to = "/categories"
  status = 301
  force = true
[[redirects]]
  from = "https://www.easeout.co/blog/css-pseudo-classes"
  to = "https://www.easeout.co/blog/2020-03-31-css-pseudo-classes"
  status = 301
  force = true
[[redirects]]
  from = "https://www.easeout.co/blog/css-pseudo-elements"
  to = "https://www.easeout.co/blog/2020-04-06-css-pseudo-elements"
  status = 301
  force = true
[[redirects]]
  from = "https://www.easeout.co/blog/easeout-weekly-7"
  to = "https://www.easeout.co/blog/2020-04-04-easeout-weekly-7"
  status = 301
  force = true
[[redirects]]
  from = "https://www.easeout.co/blog/inspirational-agency-portfolio-websites-april-2020"
  to = "https://www.easeout.co/blog/2020-04-01-inspirational-agency-portfolio-websites-april-2020"
  status = 301
  force = true